# Generated by Django 4.1.7 on 2023-04-11 03:30

import Leads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('leadNumber', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[Leads.models.checkAccountNumber])),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
