version: '3.9'
services:
  
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=leads
    volumes:
      - /data/db 
    ports:
      - 27017:27017
  postgres-demo:
    image: postgres
    container_name: postgres-demo
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Welcome
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s 
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - /home/komal/Desktop/data:/var/lib/my_data
    restart: always
  redis:
    image: redis
    container_name: redis
    ports:
      -  6379:6379
    volumes:
      - /home/komal/Desktop/data:/var/lib/my_data
    restart: always
  django:
    image: 
      django
    build: .
    tty: true
    ports:
      -  8000:8000
    depends_on:
      - mongo
      - postgres-demo
      - redis
    entrypoint: bash

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"