# Generated by Django 4.1.7 on 2023-04-11 03:30

import Bank.account.account
import Bank.transactions.transactions
import Bank.transferAmount.transferAmount
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountNumber', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[Bank.account.account.checkAccountNumber])),
                ('name', models.CharField(max_length=20)),
                ('aadharCard', models.IntegerField(blank=True, validators=[Bank.account.account.checkAadhareNumber])),
                ('type', models.CharField(choices=[('Saving', 'Saving'), ('Current', 'Current'), ('Minor', 'Minor')], default='Saving', max_length=10)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, default=10000.0, max_digits=100, validators=[Bank.account.account.chechBalance])),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('loc', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransferAmount',
            fields=[
                ('transactionId', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Withdraw', 'Withdraw'), ('Deposit', 'Deposit')], default='Deposit', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100, validators=[Bank.transferAmount.transferAmount.checkAmount])),
                ('accountNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bank.account')),
            ],
        ),
        migrations.CreateModel(
            name='Transactiona',
            fields=[
                ('transactionId', models.AutoField(primary_key=True, serialize=False)),
                ('accountNumber', models.CharField(max_length=10, validators=[Bank.transactions.transactions.checkAccountNumber])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100, validators=[Bank.transactions.transactions.checkAmount])),
                ('toAccountNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bank.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='branch_Id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Bank.branch'),
        ),
    ]
