# Generated by Django 4.1.7 on 2023-04-11 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='aadharCard',
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Home Loan', 'Home Loan'), ('Business Loan', 'Business Loan'), ('Personal Loan', 'Personal Loan'), ('Education Loan', 'Education Loan'), ('Vehicle Loan', 'Vehicle Loan')], default='Home Loan', max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('intrestRate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('timeInYears', models.IntegerField()),
                ('accountNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bank.account')),
            ],
        ),
    ]
