# Generated by Django 4.1.7 on 2023-04-13 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0002_remove_account_aadharcard_loan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactiona',
            new_name='Transaction',
        ),
    ]
